import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
}

// ---------------------------------------------------------------------- version

// One place the app's version is written down. The Android manifest, the Settings screen
// and the in-app updater all read it from here, so there is no way for the number the app
// displays to disagree with the number it compares against a GitHub release tag.
val appVersionName: String = providers.gradleProperty("pocketful.versionName").get()
val appVersionCode: Int = providers.gradleProperty("pocketful.versionCode").get().toInt()

/**
 * Hands [appVersionName] to common code as a generated source file.
 *
 * The alternative -- BuildConfig -- only exists on the Android target, and the code that
 * needs the version most (the updater's "is the release newer than me" check) is common.
 * A four-line generated file costs less than an expect/actual pair per platform.
 */
val generateAppVersion by tasks.registering {
    val versionName = appVersionName
    val versionCode = appVersionCode
    val outputDir = layout.buildDirectory.dir("generated/version/commonMain/kotlin")
    inputs.property("versionName", versionName)
    inputs.property("versionCode", versionCode)
    outputs.dir(outputDir)
    doLast {
        val target = outputDir.get().asFile.resolve("app/pocketful")
        target.mkdirs()
        target.resolve("AppVersion.kt").writeText(
            """
            package app.pocketful

            /**
             * What this build calls itself.
             *
             * Generated by the `generateAppVersion` Gradle task from `pocketful.versionName`
             * and `pocketful.versionCode` in gradle.properties. Do not edit -- edit those.
             */
            object AppVersion {
                const val NAME: String = "$versionName"
                const val CODE: Int = $versionCode

                /** The git tag a release of this version is published under. */
                val tag: String get() = "v${'$'}NAME"
            }

            """.trimIndent(),
        )
    }
}

// ---------------------------------------------------------------------- signing

/**
 * Release signing, from a file that is never committed or from CI secrets.
 *
 * Falls back to the debug key when neither is present, which keeps `assembleRelease`
 * working on a fresh clone. That fallback matters more than it looks: an APK can only
 * replace an installed app if both are signed by the same key, so a self-updating build
 * signed with a throwaway key would install once and then refuse every update after it.
 * Whichever key you ship the first APK with is the key every later one must use.
 */
val keystoreProperties = Properties().apply {
    val file = rootProject.file("keystore.properties")
    if (file.exists()) file.inputStream().use(::load)
}

fun signingSecret(property: String, environment: String): String? =
    keystoreProperties.getProperty(property)
        ?: providers.environmentVariable(environment).orNull

val releaseKeystore: String? = signingSecret("storeFile", "POCKETFUL_KEYSTORE_FILE")

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_21)
        }
    }

    sourceSets {
        // The `compose.*` accessors are deprecated in favour of explicit coordinates, but
        // material3 is published on its own version track (stable stops at 1.9.0 while the
        // rest of Compose is at 1.12.0). The plugin resolves a combination that is actually
        // tested together, so keep the accessors until material3 catches up.
        commonMain.dependencies {
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material3)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.ktor.client.core)
            implementation(libs.ktor.client.content.negotiation)
            implementation(libs.ktor.serialization.kotlinx.json)
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor3)
        }
        commonMain.get().kotlin.srcDir(generateAppVersion)
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.androidx.core.ktx)
            // The engine is only needed where the app actually runs. Ktor discovers it at
            // runtime, so common code can build an HttpClient without naming a platform.
            implementation(libs.ktor.client.okhttp)
        }
    }
}

/**
 * Resources are addressed from common code, so the generated accessor has to live at a
 * package this app actually owns rather than the plugin's default, which is derived from
 * the Gradle group and module name and changes if either is renamed.
 */
compose.resources {
    publicResClass = true
    packageOfResClass = "app.pocketful.resources"
    generateResClass = always
}

android {
    namespace = "app.pocketful"
    compileSdk = libs.versions.androidCompileSdk.get().toInt()

    defaultConfig {
        applicationId = "app.pocketful"
        minSdk = libs.versions.androidMinSdk.get().toInt()
        targetSdk = libs.versions.androidTargetSdk.get().toInt()
        versionCode = appVersionCode
        versionName = appVersionName
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    signingConfigs {
        if (releaseKeystore != null) {
            create("release") {
                storeFile = file(releaseKeystore)
                storePassword = signingSecret("storePassword", "POCKETFUL_KEYSTORE_PASSWORD")
                keyAlias = signingSecret("keyAlias", "POCKETFUL_KEY_ALIAS")
                keyPassword = signingSecret("keyPassword", "POCKETFUL_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            signingConfig = signingConfigs.findByName("release")
                ?: signingConfigs.getByName("debug")
        }
    }
}
